### PR TITLE
Support for additional Apple platforms

### PR DESCRIPTION
**Pull request by hvge**
This PR adds the following changes:
- Integrates new OpenSSL build system from cc7 `v0.2.x` library. The update brings OpenSSL `1.1.1g` 
- Adds support for tvOS platform
- Adds support for macOS Catalyst platform
- Enables bitcode on all supported Apple platforms.

### CODE REVIEW

**Comment by hvge** [comment]
Unfortunately, I have to postpone this PR, due to broken XCframework support in CocoaPods :( I need to find a workaround for our case :/

**Comment by augard** [comment]
> Unfortunately, I have to postpone this PR, due to broken XCframework support in CocoaPods :( I need to find a workaround for our case :/

It's with 1.9 beta or older release, i am just curious.

**Comment by augard** [comment]
Sorry it's out, i just looked at website where blog post is just about 1.9 beta :)

**Comment by hvge** [comment]
`1.9` is out, but still broken in our particular case, when podspec declares source codes and XCFramework together. It simply generates broken flags for the linker. I'll try to split the library into two podspecs. One with precompiled XCFW and second for the high level code. If this will not help, then the cocoapods is simply broken by design :)

This needs a more work, but don't worry, it's high on our TODO list.

**Comment by augard** [comment]
Sad that Carthage have even less support for XCFrameworks and Catalyst. If it will not work it's maybe better just to create releases and copy framework manually 😖.

**Comment by hvge** [comment]
I'm closing this PR in favor of PR #320. We just have to wait for CocoaPods to publis version `1.10` that fixes many xcframework-related issues.

**Pull request closed without merging**
